name: antrian_wiradadi
description: Antrian RSU Wiradadi Husada.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.4+7

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  animate_icons: ^2.0.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^4.9.0
  cupertino_icons: ^1.0.2
  date_picker_timeline: ^1.2.3
  dio: ^5.3.2
  expansion_tile_card: ^3.0.0
  firebase_core: ^2.1.1
  flutter:
    sdk: flutter
  flutter_animated_dialog: ^2.0.1
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.2
  google_fonts: ^5.1.0
  in_app_update: ^4.0.1
  intl: ^0.18.1
  modal_bottom_sheet: ^2.0.0
  package_info_plus: ^4.1.0
  path: ^1.8.2
  path_provider: ^2.0.11
  percent_indicator: ^4.0.0
  rxdart: ^0.27.3
  scan: ^1.6.0
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2

dependency_overrides:
  intl: ^0.17.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Rubik
  #     fonts:
  #       - asset: assets/fonts/Rubik-Regular.ttf
  #       - asset: assets/fonts/Rubik-Medium.ttf
  #         weight: 600
  #       - asset: assets/fonts/Rubik-Italic.ttf
  #         style: italic
  #       - asset: assets/fonts/Rubik-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/Rubik-SemiBold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Rubik-Bold.ttf
  #         weight: 800
  #       - asset: assets/fonts/Rubik-Black.ttf
  #         weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: images/launcher.png
